{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "3c2fa998-6d00-4722-97c3-51eaa31c9677",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting aiohappyeyeballs==2.4.3 (from -r requirements.txt (line 1))\n",
      "  Using cached aiohappyeyeballs-2.4.3-py3-none-any.whl.metadata (6.1 kB)\n",
      "Collecting aiohttp==3.10.10 (from -r requirements.txt (line 2))\n",
      "  Using cached aiohttp-3.10.10-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.6 kB)\n",
      "Requirement already satisfied: aiosignal==1.3.1 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (1.3.1)\n",
      "Collecting aiostream==0.5.2 (from -r requirements.txt (line 4))\n",
      "  Using cached aiostream-0.5.2-py3-none-any.whl.metadata (9.9 kB)\n",
      "Requirement already satisfied: annotated-types==0.7.0 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (0.7.0)\n",
      "Collecting anyio==4.6.2 (from -r requirements.txt (line 6))\n",
      "  Using cached anyio-4.6.2-py3-none-any.whl.metadata (4.7 kB)\n",
      "Requirement already satisfied: async-timeout==4.0.3 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (4.0.3)\n",
      "Collecting attrs==24.2.0 (from -r requirements.txt (line 8))\n",
      "  Using cached attrs-24.2.0-py3-none-any.whl.metadata (11 kB)\n",
      "Collecting certifi==2024.8.30 (from -r requirements.txt (line 9))\n",
      "  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)\n",
      "Requirement already satisfied: click==8.1.7 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 10)) (8.1.7)\n",
      "Requirement already satisfied: colorama==0.4.6 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 11)) (0.4.6)\n",
      "Requirement already satisfied: exceptiongroup==1.2.2 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 12)) (1.2.2)\n",
      "Collecting fastapi==0.115.2 (from -r requirements.txt (line 13))\n",
      "  Using cached fastapi-0.115.2-py3-none-any.whl.metadata (27 kB)\n",
      "Collecting filelock==3.16.1 (from -r requirements.txt (line 14))\n",
      "  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)\n",
      "Requirement already satisfied: frozenlist==1.4.1 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 15)) (1.4.1)\n",
      "Collecting fsspec==2024.9.0 (from -r requirements.txt (line 16))\n",
      "  Using cached fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)\n",
      "Collecting grpclib==0.4.7 (from -r requirements.txt (line 17))\n",
      "  Using cached grpclib-0.4.7-py3-none-any.whl\n",
      "Requirement already satisfied: h2==4.1.0 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 18)) (4.1.0)\n",
      "Requirement already satisfied: hpack==4.0.0 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 19)) (4.0.0)\n",
      "Requirement already satisfied: hyperframe==6.0.1 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 20)) (6.0.1)\n",
      "Collecting idna==3.10 (from -r requirements.txt (line 21))\n",
      "  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)\n",
      "Collecting intel-openmp==2021.4.0 (from -r requirements.txt (line 22))\n",
      "  Using cached intel_openmp-2021.4.0-py2.py3-none-manylinux1_x86_64.whl.metadata (1.1 kB)\n",
      "Requirement already satisfied: Jinja2==3.1.4 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 23)) (3.1.4)\n",
      "Collecting lightning-utilities==0.11.7 (from -r requirements.txt (line 24))\n",
      "  Using cached lightning_utilities-0.11.7-py3-none-any.whl.metadata (5.2 kB)\n",
      "Requirement already satisfied: markdown-it-py==3.0.0 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 25)) (3.0.0)\n",
      "Collecting MarkupSafe==3.0.1 (from -r requirements.txt (line 26))\n",
      "  Using cached MarkupSafe-3.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)\n",
      "Requirement already satisfied: mdurl==0.1.2 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 27)) (0.1.2)\n",
      "Collecting mkl==2021.4.0 (from -r requirements.txt (line 28))\n",
      "  Using cached mkl-2021.4.0-py2.py3-none-manylinux1_x86_64.whl.metadata (1.3 kB)\n",
      "Collecting modal==0.64.178 (from -r requirements.txt (line 29))\n",
      "  Using cached modal-0.64.178-py3-none-any.whl.metadata (2.4 kB)\n",
      "Requirement already satisfied: mpmath==1.3.0 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 30)) (1.3.0)\n",
      "Collecting multidict==6.1.0 (from -r requirements.txt (line 31))\n",
      "  Using cached multidict-6.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.0 kB)\n",
      "Collecting networkx==3.4.1 (from -r requirements.txt (line 32))\n",
      "  Using cached networkx-3.4.1-py3-none-any.whl.metadata (6.3 kB)\n",
      "Requirement already satisfied: numpy==1.26.4 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 33)) (1.26.4)\n",
      "Requirement already satisfied: packaging==24.1 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 34)) (24.1)\n",
      "Collecting pandas==2.2.3 (from -r requirements.txt (line 35))\n",
      "  Using cached pandas-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)\n",
      "Collecting propcache==0.2.0 (from -r requirements.txt (line 36))\n",
      "  Using cached propcache-0.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.7 kB)\n",
      "Collecting protobuf==4.25.5 (from -r requirements.txt (line 37))\n",
      "  Using cached protobuf-4.25.5-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)\n",
      "Collecting pydantic==2.9.2 (from -r requirements.txt (line 38))\n",
      "  Using cached pydantic-2.9.2-py3-none-any.whl.metadata (149 kB)\n",
      "Collecting pydantic_core==2.23.4 (from -r requirements.txt (line 39))\n",
      "  Using cached pydantic_core-2.23.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)\n",
      "Requirement already satisfied: Pygments==2.18.0 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 40)) (2.18.0)\n",
      "Collecting python-dateutil==2.9.0.post0 (from -r requirements.txt (line 41))\n",
      "  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)\n",
      "Collecting pytorch-lightning==2.4.0 (from -r requirements.txt (line 42))\n",
      "  Using cached pytorch_lightning-2.4.0-py3-none-any.whl.metadata (21 kB)\n",
      "Collecting pytz==2024.2 (from -r requirements.txt (line 43))\n",
      "  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)\n",
      "Requirement already satisfied: PyYAML==6.0.2 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 44)) (6.0.2)\n",
      "Collecting rich==13.9.2 (from -r requirements.txt (line 45))\n",
      "  Using cached rich-13.9.2-py3-none-any.whl.metadata (18 kB)\n",
      "Requirement already satisfied: shellingham==1.5.4 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 46)) (1.5.4)\n",
      "Collecting sigtools==4.0.1 (from -r requirements.txt (line 47))\n",
      "  Using cached sigtools-4.0.1-py2.py3-none-any.whl.metadata (2.4 kB)\n",
      "Requirement already satisfied: six==1.16.0 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 48)) (1.16.0)\n",
      "Requirement already satisfied: sniffio==1.3.1 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 49)) (1.3.1)\n",
      "Collecting starlette==0.39.2 (from -r requirements.txt (line 50))\n",
      "  Using cached starlette-0.39.2-py3-none-any.whl.metadata (6.0 kB)\n",
      "Collecting sympy==1.13.3 (from -r requirements.txt (line 51))\n",
      "  Using cached sympy-1.13.3-py3-none-any.whl.metadata (12 kB)\n",
      "Collecting synchronicity==0.8.2 (from -r requirements.txt (line 52))\n",
      "  Using cached synchronicity-0.8.2-py3-none-any.whl.metadata (8.3 kB)\n",
      "Collecting tbb==2021.13.1 (from -r requirements.txt (line 53))\n",
      "  Using cached tbb-2021.13.1-py2.py3-none-manylinux1_x86_64.whl.metadata (1.0 kB)\n",
      "Requirement already satisfied: timm in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 54)) (0.9.16)\n",
      "Collecting toml==0.10.2 (from -r requirements.txt (line 55))\n",
      "  Using cached toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)\n",
      "Collecting torch==2.3.1 (from -r requirements.txt (line 56))\n",
      "  Using cached torch-2.3.1-cp311-cp311-manylinux1_x86_64.whl.metadata (26 kB)\n",
      "Collecting torchmetrics==1.4.3 (from -r requirements.txt (line 57))\n",
      "  Using cached torchmetrics-1.4.3-py3-none-any.whl.metadata (19 kB)\n",
      "Requirement already satisfied: tqdm==4.66.5 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 58)) (4.66.5)\n",
      "Collecting typer==0.12.5 (from -r requirements.txt (line 59))\n",
      "  Using cached typer-0.12.5-py3-none-any.whl.metadata (15 kB)\n",
      "Collecting types-certifi==2021.10.8.3 (from -r requirements.txt (line 60))\n",
      "  Using cached types_certifi-2021.10.8.3-py3-none-any.whl.metadata (1.4 kB)\n",
      "Collecting types-toml==0.10.8.20240310 (from -r requirements.txt (line 61))\n",
      "  Using cached types_toml-0.10.8.20240310-py3-none-any.whl.metadata (1.5 kB)\n",
      "Requirement already satisfied: typing_extensions==4.12.2 in /opt/conda/lib/python3.11/site-packages (from -r requirements.txt (line 62)) (4.12.2)\n",
      "Collecting tzdata==2024.2 (from -r requirements.txt (line 63))\n",
      "  Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)\n",
      "Collecting watchfiles==0.24.0 (from -r requirements.txt (line 64))\n",
      "  Using cached watchfiles-0.24.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)\n",
      "Collecting yarl==1.15.2 (from -r requirements.txt (line 65))\n",
      "  Using cached yarl-1.15.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (56 kB)\n",
      "Collecting einops (from -r requirements.txt (line 66))\n",
      "  Using cached einops-0.8.0-py3-none-any.whl.metadata (12 kB)\n",
      "Collecting labml_nn (from -r requirements.txt (line 67))\n",
      "  Using cached labml_nn-0.4.137-py3-none-any.whl.metadata (9.2 kB)\n",
      "Collecting labml_helpers (from -r requirements.txt (line 68))\n",
      "  Using cached labml_helpers-0.4.89-py3-none-any.whl.metadata (1.4 kB)\n",
      "Requirement already satisfied: setuptools in /opt/conda/lib/python3.11/site-packages (from lightning-utilities==0.11.7->-r requirements.txt (line 24)) (72.1.0)\n",
      "Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.3.1->-r requirements.txt (line 56))\n",
      "  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)\n",
      "Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.3.1->-r requirements.txt (line 56))\n",
      "  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)\n",
      "Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.3.1->-r requirements.txt (line 56))\n",
      "  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)\n",
      "Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.3.1->-r requirements.txt (line 56))\n",
      "  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)\n",
      "Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.3.1->-r requirements.txt (line 56))\n",
      "  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)\n",
      "Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.3.1->-r requirements.txt (line 56))\n",
      "  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)\n",
      "Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.3.1->-r requirements.txt (line 56))\n",
      "  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)\n",
      "Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.3.1->-r requirements.txt (line 56))\n",
      "  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)\n",
      "Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.3.1->-r requirements.txt (line 56))\n",
      "  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)\n",
      "Collecting nvidia-nccl-cu12==2.20.5 (from torch==2.3.1->-r requirements.txt (line 56))\n",
      "  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)\n",
      "Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.3.1->-r requirements.txt (line 56))\n",
      "  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)\n",
      "Collecting triton==2.3.1 (from torch==2.3.1->-r requirements.txt (line 56))\n",
      "  Using cached triton-2.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)\n",
      "Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch==2.3.1->-r requirements.txt (line 56))\n",
      "  Using cached nvidia_nvjitlink_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)\n",
      "Requirement already satisfied: torchvision in /opt/conda/lib/python3.11/site-packages (from timm->-r requirements.txt (line 54)) (0.18.1a0+405940f)\n",
      "Requirement already satisfied: huggingface_hub in /opt/conda/lib/python3.11/site-packages (from timm->-r requirements.txt (line 54)) (0.24.5)\n",
      "Requirement already satisfied: safetensors in /opt/conda/lib/python3.11/site-packages (from timm->-r requirements.txt (line 54)) (0.4.4)\n",
      "Collecting labml==0.4.168 (from labml_nn->-r requirements.txt (line 67))\n",
      "  Using cached labml-0.4.168-py3-none-any.whl.metadata (7.5 kB)\n",
      "Collecting torchtext (from labml_nn->-r requirements.txt (line 67))\n",
      "  Using cached torchtext-0.18.0-cp311-cp311-manylinux1_x86_64.whl.metadata (7.9 kB)\n",
      "Collecting fairscale (from labml_nn->-r requirements.txt (line 67))\n",
      "  Using cached fairscale-0.4.13-py3-none-any.whl\n",
      "Requirement already satisfied: gitpython in /opt/conda/lib/python3.11/site-packages (from labml==0.4.168->labml_nn->-r requirements.txt (line 67)) (3.1.43)\n",
      "Requirement already satisfied: requests in /opt/conda/lib/python3.11/site-packages (from huggingface_hub->timm->-r requirements.txt (line 54)) (2.32.3)\n",
      "Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /opt/conda/lib/python3.11/site-packages (from torchvision->timm->-r requirements.txt (line 54)) (10.4.0)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/conda/lib/python3.11/site-packages (from gitpython->labml==0.4.168->labml_nn->-r requirements.txt (line 67)) (4.0.11)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests->huggingface_hub->timm->-r requirements.txt (line 54)) (3.3.2)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.11/site-packages (from requests->huggingface_hub->timm->-r requirements.txt (line 54)) (1.26.19)\n",
      "Requirement already satisfied: smmap<6,>=3.0.1 in /opt/conda/lib/python3.11/site-packages (from gitdb<5,>=4.0.1->gitpython->labml==0.4.168->labml_nn->-r requirements.txt (line 67)) (5.0.0)\n",
      "\u001b[33mWARNING: The candidate selected for download or install is a yanked version: 'anyio' candidate (version 4.6.2 at https://files.pythonhosted.org/packages/3e/dc/a27d58194ddcbeb295500cc6bf233d4dfb34a95a10ca5dbe4ff8454399e4/anyio-4.6.2-py3-none-any.whl (from https://pypi.org/simple/anyio/) (requires-python:>=3.8))\n",
      "Reason for being yanked: This was 4.5.2 code, mistagged\u001b[0m\u001b[33m\n",
      "\u001b[0mUsing cached aiohappyeyeballs-2.4.3-py3-none-any.whl (14 kB)\n",
      "Using cached aiohttp-3.10.10-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)\n",
      "Using cached aiostream-0.5.2-py3-none-any.whl (39 kB)\n",
      "Using cached anyio-4.6.2-py3-none-any.whl (89 kB)\n",
      "Using cached attrs-24.2.0-py3-none-any.whl (63 kB)\n",
      "Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)\n",
      "Using cached fastapi-0.115.2-py3-none-any.whl (94 kB)\n",
      "Using cached filelock-3.16.1-py3-none-any.whl (16 kB)\n",
      "Using cached fsspec-2024.9.0-py3-none-any.whl (179 kB)\n",
      "Using cached idna-3.10-py3-none-any.whl (70 kB)\n",
      "Using cached intel_openmp-2021.4.0-py2.py3-none-manylinux1_x86_64.whl (9.9 MB)\n",
      "Using cached lightning_utilities-0.11.7-py3-none-any.whl (26 kB)\n",
      "Using cached MarkupSafe-3.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23 kB)\n",
      "Using cached mkl-2021.4.0-py2.py3-none-manylinux1_x86_64.whl (280.9 MB)\n",
      "Using cached modal-0.64.178-py3-none-any.whl (552 kB)\n",
      "Using cached multidict-6.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (129 kB)\n",
      "Using cached networkx-3.4.1-py3-none-any.whl (1.7 MB)\n",
      "Using cached pandas-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)\n",
      "Using cached propcache-0.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (236 kB)\n",
      "Using cached protobuf-4.25.5-cp37-abi3-manylinux2014_x86_64.whl (294 kB)\n",
      "Using cached pydantic-2.9.2-py3-none-any.whl (434 kB)\n",
      "Using cached pydantic_core-2.23.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)\n",
      "Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)\n",
      "Using cached pytorch_lightning-2.4.0-py3-none-any.whl (815 kB)\n",
      "Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)\n",
      "Using cached rich-13.9.2-py3-none-any.whl (242 kB)\n",
      "Using cached sigtools-4.0.1-py2.py3-none-any.whl (76 kB)\n",
      "Using cached starlette-0.39.2-py3-none-any.whl (73 kB)\n",
      "Using cached sympy-1.13.3-py3-none-any.whl (6.2 MB)\n",
      "Using cached synchronicity-0.8.2-py3-none-any.whl (31 kB)\n",
      "Using cached tbb-2021.13.1-py2.py3-none-manylinux1_x86_64.whl (5.4 MB)\n",
      "Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)\n",
      "Using cached torch-2.3.1-cp311-cp311-manylinux1_x86_64.whl (779.2 MB)\n",
      "Using cached torchmetrics-1.4.3-py3-none-any.whl (869 kB)\n",
      "Using cached typer-0.12.5-py3-none-any.whl (47 kB)\n",
      "Using cached types_certifi-2021.10.8.3-py3-none-any.whl (2.1 kB)\n",
      "Using cached types_toml-0.10.8.20240310-py3-none-any.whl (4.8 kB)\n",
      "Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)\n",
      "Using cached watchfiles-0.24.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (425 kB)\n",
      "Using cached yarl-1.15.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (337 kB)\n",
      "Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)\n",
      "Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)\n",
      "Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)\n",
      "Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)\n",
      "Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)\n",
      "Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)\n",
      "Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)\n",
      "Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)\n",
      "Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)\n",
      "Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)\n",
      "Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)\n",
      "Using cached triton-2.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (168.1 MB)\n",
      "Using cached einops-0.8.0-py3-none-any.whl (43 kB)\n",
      "Using cached labml_nn-0.4.137-py3-none-any.whl (443 kB)\n",
      "Using cached labml_helpers-0.4.89-py3-none-any.whl (24 kB)\n",
      "Using cached labml-0.4.168-py3-none-any.whl (130 kB)\n",
      "Using cached torchtext-0.18.0-cp311-cp311-manylinux1_x86_64.whl (2.0 MB)\n",
      "Using cached nvidia_nvjitlink_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl (19.7 MB)\n",
      "Installing collected packages: types-certifi, tbb, pytz, intel-openmp, tzdata, types-toml, toml, sympy, python-dateutil, pydantic_core, protobuf, propcache, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, networkx, multidict, mkl, MarkupSafe, lightning-utilities, idna, fsspec, filelock, einops, certifi, attrs, aiostream, aiohappyeyeballs, yarl, triton, sigtools, rich, pydantic, pandas, nvidia-cusparse-cu12, nvidia-cudnn-cu12, grpclib, anyio, watchfiles, typer, synchronicity, starlette, nvidia-cusolver-cu12, labml, aiohttp, torch, fastapi, torchtext, torchmetrics, modal, labml_helpers, fairscale, pytorch-lightning, labml_nn\n",
      "  Attempting uninstall: pytz\n",
      "    Found existing installation: pytz 2023.3\n",
      "    Uninstalling pytz-2023.3:\n",
      "      Successfully uninstalled pytz-2023.3\n",
      "  Attempting uninstall: tzdata\n",
      "    Found existing installation: tzdata 2024.1\n",
      "    Uninstalling tzdata-2024.1:\n",
      "      Successfully uninstalled tzdata-2024.1\n",
      "  Attempting uninstall: sympy\n",
      "    Found existing installation: sympy 1.13.2\n",
      "    Uninstalling sympy-1.13.2:\n",
      "      Successfully uninstalled sympy-1.13.2\n",
      "  Attempting uninstall: python-dateutil\n",
      "    Found existing installation: python-dateutil 2.9.0\n",
      "    Uninstalling python-dateutil-2.9.0:\n",
      "      Successfully uninstalled python-dateutil-2.9.0\n",
      "  Attempting uninstall: pydantic_core\n",
      "    Found existing installation: pydantic_core 2.18.4\n",
      "    Uninstalling pydantic_core-2.18.4:\n",
      "      Successfully uninstalled pydantic_core-2.18.4\n",
      "  Attempting uninstall: protobuf\n",
      "    Found existing installation: protobuf 4.25.3\n",
      "    Uninstalling protobuf-4.25.3:\n",
      "      Successfully uninstalled protobuf-4.25.3\n",
      "  Attempting uninstall: networkx\n",
      "    Found existing installation: networkx 3.3\n",
      "    Uninstalling networkx-3.3:\n",
      "      Successfully uninstalled networkx-3.3\n",
      "  Attempting uninstall: multidict\n",
      "    Found existing installation: multidict 6.0.5\n",
      "    Uninstalling multidict-6.0.5:\n",
      "      Successfully uninstalled multidict-6.0.5\n",
      "  Attempting uninstall: MarkupSafe\n",
      "    Found existing installation: MarkupSafe 2.1.5\n",
      "    Uninstalling MarkupSafe-2.1.5:\n",
      "      Successfully uninstalled MarkupSafe-2.1.5\n",
      "  Attempting uninstall: lightning-utilities\n",
      "    Found existing installation: lightning-utilities 0.11.6\n",
      "    Uninstalling lightning-utilities-0.11.6:\n",
      "      Successfully uninstalled lightning-utilities-0.11.6\n",
      "  Attempting uninstall: idna\n",
      "    Found existing installation: idna 3.7\n",
      "    Uninstalling idna-3.7:\n",
      "      Successfully uninstalled idna-3.7\n",
      "  Attempting uninstall: fsspec\n",
      "    Found existing installation: fsspec 2023.6.0\n",
      "    Uninstalling fsspec-2023.6.0:\n",
      "      Successfully uninstalled fsspec-2023.6.0\n",
      "  Attempting uninstall: filelock\n",
      "    Found existing installation: filelock 3.15.4\n",
      "    Uninstalling filelock-3.15.4:\n",
      "      Successfully uninstalled filelock-3.15.4\n",
      "  Attempting uninstall: certifi\n",
      "    Found existing installation: certifi 2024.7.4\n",
      "    Uninstalling certifi-2024.7.4:\n",
      "      Successfully uninstalled certifi-2024.7.4\n",
      "  Attempting uninstall: attrs\n",
      "    Found existing installation: attrs 23.2.0\n",
      "    Uninstalling attrs-23.2.0:\n",
      "      Successfully uninstalled attrs-23.2.0\n",
      "  Attempting uninstall: yarl\n",
      "    Found existing installation: yarl 1.9.4\n",
      "    Uninstalling yarl-1.9.4:\n",
      "      Successfully uninstalled yarl-1.9.4\n",
      "  Attempting uninstall: rich\n",
      "    Found existing installation: rich 13.7.1\n",
      "    Uninstalling rich-13.7.1:\n",
      "      Successfully uninstalled rich-13.7.1\n",
      "  Attempting uninstall: pydantic\n",
      "    Found existing installation: pydantic 1.10.17\n",
      "    Uninstalling pydantic-1.10.17:\n",
      "      Successfully uninstalled pydantic-1.10.17\n",
      "  Attempting uninstall: pandas\n",
      "    Found existing installation: pandas 2.2.2\n",
      "    Uninstalling pandas-2.2.2:\n",
      "      Successfully uninstalled pandas-2.2.2\n",
      "  Attempting uninstall: anyio\n",
      "    Found existing installation: anyio 4.4.0\n",
      "    Uninstalling anyio-4.4.0:\n",
      "      Successfully uninstalled anyio-4.4.0\n",
      "  Attempting uninstall: typer\n",
      "    Found existing installation: typer 0.9.4\n",
      "    Uninstalling typer-0.9.4:\n",
      "      Successfully uninstalled typer-0.9.4\n",
      "  Attempting uninstall: starlette\n",
      "    Found existing installation: starlette 0.37.2\n",
      "    Uninstalling starlette-0.37.2:\n",
      "      Successfully uninstalled starlette-0.37.2\n",
      "  Attempting uninstall: aiohttp\n",
      "    Found existing installation: aiohttp 3.9.5\n",
      "    Uninstalling aiohttp-3.9.5:\n",
      "      Successfully uninstalled aiohttp-3.9.5\n",
      "  Attempting uninstall: torch\n",
      "    Found existing installation: torch 2.3.1.post300\n",
      "    Uninstalling torch-2.3.1.post300:\n",
      "      Successfully uninstalled torch-2.3.1.post300\n",
      "  Attempting uninstall: fastapi\n",
      "    Found existing installation: fastapi 0.110.3\n",
      "    Uninstalling fastapi-0.110.3:\n",
      "      Successfully uninstalled fastapi-0.110.3\n",
      "  Attempting uninstall: torchmetrics\n",
      "    Found existing installation: torchmetrics 1.2.1\n",
      "    Uninstalling torchmetrics-1.2.1:\n",
      "      Successfully uninstalled torchmetrics-1.2.1\n",
      "  Attempting uninstall: pytorch-lightning\n",
      "    Found existing installation: pytorch-lightning 2.3.3\n",
      "    Uninstalling pytorch-lightning-2.3.3:\n",
      "      Successfully uninstalled pytorch-lightning-2.3.3\n",
      "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "autogluon-multimodal 1.1.1 requires nvidia-ml-py3==7.352.0, which is not installed.\n",
      "jupyter-ai 2.20.0 requires faiss-cpu<=1.8.0, which is not installed.\n",
      "amazon-sagemaker-sql-magic 0.1.3 requires sqlparse==0.5.0, but you have sqlparse 0.5.1 which is incompatible.\n",
      "autogluon-core 1.1.1 requires scikit-learn<1.4.1,>=1.3.0, but you have scikit-learn 1.4.2 which is incompatible.\n",
      "autogluon-features 1.1.1 requires scikit-learn<1.4.1,>=1.3.0, but you have scikit-learn 1.4.2 which is incompatible.\n",
      "autogluon-multimodal 1.1.1 requires omegaconf<2.3.0,>=2.1.1, but you have omegaconf 2.3.0 which is incompatible.\n",
      "autogluon-multimodal 1.1.1 requires scikit-learn<1.4.1,>=1.3.0, but you have scikit-learn 1.4.2 which is incompatible.\n",
      "autogluon-multimodal 1.1.1 requires torchmetrics<1.3.0,>=1.2.0, but you have torchmetrics 1.4.3 which is incompatible.\n",
      "autogluon-tabular 1.1.1 requires scikit-learn<1.4.1,>=1.3.0, but you have scikit-learn 1.4.2 which is incompatible.\n",
      "autogluon-timeseries 1.1.1 requires gluonts==0.15.1, but you have gluonts 0.14.3 which is incompatible.\n",
      "autogluon-timeseries 1.1.1 requires pytorch-lightning<2.4,>=2.2, but you have pytorch-lightning 2.4.0 which is incompatible.\n",
      "autovizwidget 0.21.0 requires pandas<2.0.0,>=0.20.1, but you have pandas 2.2.3 which is incompatible.\n",
      "datasets 2.21.0 requires fsspec[http]<=2024.6.1,>=2023.1.0, but you have fsspec 2024.9.0 which is incompatible.\n",
      "hdijupyterutils 0.21.0 requires pandas<2.0.0,>=0.17.1, but you have pandas 2.2.3 which is incompatible.\n",
      "jupyter-scheduler 2.7.1 requires fsspec==2023.6.0, but you have fsspec 2024.9.0 which is incompatible.\n",
      "jupyter-scheduler 2.7.1 requires pytz==2023.3, but you have pytz 2024.2 which is incompatible.\n",
      "langchain-community 0.2.12 requires langchain<0.3.0,>=0.2.13, but you have langchain 0.2.5 which is incompatible.\n",
      "sagemaker 2.227.0 requires attrs<24,>=23.1.0, but you have attrs 24.2.0 which is incompatible.\n",
      "sagemaker 2.227.0 requires boto3<2.0,>=1.34.142, but you have boto3 1.34.131 which is incompatible.\n",
      "sparkmagic 0.21.0 requires pandas<2.0.0,>=0.17.1, but you have pandas 2.2.3 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0mSuccessfully installed MarkupSafe-3.0.1 aiohappyeyeballs-2.4.3 aiohttp-3.10.10 aiostream-0.5.2 anyio-4.6.2 attrs-24.2.0 certifi-2024.8.30 einops-0.8.0 fairscale-0.4.13 fastapi-0.115.2 filelock-3.16.1 fsspec-2023.6.0 grpclib-0.4.7 idna-3.10 intel-openmp-2021.4.0 labml-0.4.168 labml_helpers-0.4.89 labml_nn-0.4.137 lightning-utilities-0.11.7 mkl-2021.4.0 modal-0.64.178 multidict-6.1.0 networkx-3.4.1 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.6.77 nvidia-nvtx-cu12-12.1.105 pandas-2.2.3 propcache-0.2.0 protobuf-4.25.5 pydantic-2.7.3 pydantic_core-2.23.4 python-dateutil-2.9.0.post0 pytorch-lightning-2.4.0 pytz-2023.3 rich-13.9.2 sigtools-4.0.1 starlette-0.39.2 sympy-1.13.3 synchronicity-0.8.2 tbb-2021.13.1 toml-0.10.2 torch-2.3.1 torchmetrics-1.4.3 torchtext-0.18.0 triton-2.3.1 typer-0.12.5 types-certifi-2021.10.8.3 types-toml-0.10.8.20240310 tzdata-2024.2 watchfiles-0.24.0 yarl-1.15.2\n"
     ]
    }
   ],
   "source": [
    "!pip install -r requirements.txt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0b7872d9-24ec-4ce4-8054-bda552feb148",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "test\n"
     ]
    }
   ],
   "source": [
    "import boto3\n",
    "import os \n",
    "\n",
    "s3_resource = boto3.resource('s3')\n",
    "bucket = s3_resource.Bucket('sgn-sagemaker-dev') \n",
    "os.makedirs(\"data\",exist_ok=True)\n",
    "for obj in bucket.objects.filter(Prefix = 'patient_retention/data'):\n",
    "    if \".\" in os.path.basename(obj.key):\n",
    "        if(not os.path.exists(os.path.basename(obj.key))):\n",
    "            bucket.download_file(obj.key, os.path.join('data',os.path.basename(obj.key)))\n",
    "print(\"test\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "b4f7c66a-9183-4912-98a8-20032e982166",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pytorch_lightning as pl\n",
    "from pytorch_lightning.callbacks import ModelCheckpoint,EarlyStopping\n",
    "from pytorch_lightning.loggers import CSVLogger\n",
    "import torch\n",
    "\n",
    "from data_module import PatientDataModule\n",
    "from model_module import PatientModelModule \n",
    "\n",
    "from train_util.utils import load_hparams_from_yaml\n",
    "\n",
    "model_name = 'lstm'\n",
    "cur_date = datetime.now().isoformat()\n",
    "\n",
    "hparams_path = f\"configs/{model_name}.yaml\"\n",
    "hparams = load_hparams_from_yaml(hparams_path)\n",
    "datamodule = PatientDataModule(hparams_path)\n",
    "model = PatientModelModule(hparams_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "dad27b04-1837-4849-a9d5-40ae8bff60f5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "GPU available: True (cuda), used: True\n",
      "TPU available: False, using: 0 TPU cores\n",
      "HPU available: False, using: 0 HPUs\n"
     ]
    }
   ],
   "source": [
    "\n",
    "checkpoint_cb = ModelCheckpoint(\n",
    "    dirpath=f\"log/{model_name}-{}/checkpoints\",\n",
    "    filename=f'{hparams[\"model\"][\"name\"]}' + \"_epoch({epoch:02d})_step({step:04d})_val_{val/mse:.4f}\",\n",
    "    \n",
    "    monitor=\"val/mse\",\n",
    "    mode=\"min\",\n",
    "    \n",
    "    auto_insert_metric_name=False,\n",
    "    \n",
    "    save_last=True,\n",
    "    save_weights_only=True,\n",
    "    save_top_k=3,\n",
    ")\n",
    "csv_logger = CSVLogger(\n",
    "    save_dir=\"/saved/logs\"\n",
    ")\n",
    "early_stopping_cb = EarlyStopping(\n",
    "    monitor=\"val/mse\",\n",
    "    mode=\"min\",\n",
    "    patience=5,\n",
    "    min_delta = 0\n",
    ")\n",
    "\n",
    "# input_temp = torch.randn((4,16,49))\n",
    "# output = model.net(input_temp)\n",
    "# print(output.shape)\n",
    "\n",
    "trainer = pl.Trainer(\n",
    "    accelerator=\"gpu\",\n",
    "    devices=[0],\n",
    "    logger=csv_logger,\n",
    "    precision=32,\n",
    "    max_epochs=hparams[\"training_param\"][\"max_epochs\"],\n",
    "    check_val_every_n_epoch=1,\n",
    "    callbacks=[\n",
    "        checkpoint_cb,\n",
    "        early_stopping_cb\n",
    "    ],\n",
    "    log_every_n_steps=5\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "6bb5701e-6f41-48e6-89c7-1281ecc20668",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Missing logger folder: /root/saved/logs/lightning_logs\n"
     ]
    },
    {
     "ename": "PermissionError",
     "evalue": "[Errno 13] Permission denied: '/root/saved'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mPermissionError\u001b[0m                           Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[6], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mtrainer\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mmodel\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mmodel\u001b[49m\u001b[43m,\u001b[49m\u001b[43mdatamodule\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mdatamodule\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m      2\u001b[0m trainer\u001b[38;5;241m.\u001b[39mtest(model\u001b[38;5;241m=\u001b[39mmodel,datamodule\u001b[38;5;241m=\u001b[39mdatamodule,ckpt_path\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mlast\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m      3\u001b[0m trainer\u001b[38;5;241m.\u001b[39mtest(model\u001b[38;5;241m=\u001b[39mmodel,datamodule\u001b[38;5;241m=\u001b[39mdatamodule,ckpt_path\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mbest\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py:543\u001b[0m, in \u001b[0;36mfit\u001b[0;34m(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)\u001b[0m\n\u001b[1;32m    537\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mtraining \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mTrue\u001b[39;00m\n\u001b[1;32m    538\u001b[0m     call\u001b[38;5;241m.\u001b[39m_call_and_handle_interrupt(\n\u001b[1;32m    539\u001b[0m         \u001b[38;5;28mself\u001b[39m, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path\n\u001b[1;32m    540\u001b[0m     )\n\u001b[1;32m    542\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_fit_impl\u001b[39m(\n\u001b[0;32m--> 543\u001b[0m     \u001b[38;5;28mself\u001b[39m,\n\u001b[1;32m    544\u001b[0m     model: \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mpl.LightningModule\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[1;32m    545\u001b[0m     train_dataloaders: Optional[Union[TRAIN_DATALOADERS, LightningDataModule]] \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[1;32m    546\u001b[0m     val_dataloaders: Optional[EVAL_DATALOADERS] \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[1;32m    547\u001b[0m     datamodule: Optional[LightningDataModule] \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[1;32m    548\u001b[0m     ckpt_path: Optional[_PATH] \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[1;32m    549\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    550\u001b[0m     log\u001b[38;5;241m.\u001b[39mdebug(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__class__\u001b[39m\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m: trainer fit stage\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m    552\u001b[0m     \u001b[38;5;66;03m# if a datamodule comes in as the second arg, then fix it for the user\u001b[39;00m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py:44\u001b[0m, in \u001b[0;36m_call_and_handle_interrupt\u001b[0;34m(trainer, trainer_fn, *args, **kwargs)\u001b[0m\n\u001b[1;32m     34\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_call_and_handle_interrupt\u001b[39m(trainer: \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mpl.Trainer\u001b[39m\u001b[38;5;124m\"\u001b[39m, trainer_fn: Callable, \u001b[38;5;241m*\u001b[39margs: Any, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs: Any) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m Any:\n\u001b[1;32m     35\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124mr\u001b[39m\u001b[38;5;124;03m\"\"\"Error handling, intended to be used only for main trainer function entry points (fit, validate, test, predict)\u001b[39;00m\n\u001b[1;32m     36\u001b[0m \u001b[38;5;124;03m    as all errors should funnel through them.\u001b[39;00m\n\u001b[1;32m     37\u001b[0m \n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     42\u001b[0m \n\u001b[1;32m     43\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[0;32m---> 44\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     45\u001b[0m         \u001b[38;5;28;01mif\u001b[39;00m trainer\u001b[38;5;241m.\u001b[39mstrategy\u001b[38;5;241m.\u001b[39mlauncher \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m     46\u001b[0m             \u001b[38;5;28;01mreturn\u001b[39;00m trainer\u001b[38;5;241m.\u001b[39mstrategy\u001b[38;5;241m.\u001b[39mlauncher\u001b[38;5;241m.\u001b[39mlaunch(trainer_fn, \u001b[38;5;241m*\u001b[39margs, trainer\u001b[38;5;241m=\u001b[39mtrainer, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py:579\u001b[0m, in \u001b[0;36m_fit_impl\u001b[0;34m(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)\u001b[0m\n\u001b[1;32m      0\u001b[0m <Error retrieving source code with stack_data see ipython/ipython#13598>\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py:948\u001b[0m, in \u001b[0;36m_run\u001b[0;34m(self, model, ckpt_path)\u001b[0m\n\u001b[1;32m    945\u001b[0m call\u001b[38;5;241m.\u001b[39m_call_configure_model(\u001b[38;5;28mself\u001b[39m)\n\u001b[1;32m    947\u001b[0m \u001b[38;5;66;03m# check if we should delay restoring checkpoint till later\u001b[39;00m\n\u001b[0;32m--> 948\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mstrategy\u001b[38;5;241m.\u001b[39mrestore_checkpoint_after_setup:\n\u001b[1;32m    949\u001b[0m     log\u001b[38;5;241m.\u001b[39mdebug(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__class__\u001b[39m\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m: restoring module and callbacks from checkpoint path: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mckpt_path\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m    950\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_checkpoint_connector\u001b[38;5;241m.\u001b[39m_restore_modules_and_callbacks(ckpt_path)\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py:88\u001b[0m, in \u001b[0;36m_call_setup_hook\u001b[0;34m(trainer)\u001b[0m\n\u001b[1;32m     85\u001b[0m assert trainer.state.fn is not None\n\u001b[1;32m     86\u001b[0m fn = trainer.state.fn\n\u001b[0;32m---> 88\u001b[0m # It is too early to move the model to the device, but we fake the `LightningModule.device` property\n\u001b[1;32m     89\u001b[0m # so the user can access it in the `LightningModule.setup` hook\n\u001b[1;32m     90\u001b[0m for module in trainer.lightning_module.modules():\n\u001b[1;32m     91\u001b[0m     if isinstance(module, _DeviceDtypeModuleMixin):\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/lightning_fabric/loggers/logger.py:118\u001b[0m, in \u001b[0;36mrank_zero_experiment.<locals>.experiment\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    116\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m rank_zero_only\u001b[38;5;241m.\u001b[39mrank \u001b[38;5;241m>\u001b[39m \u001b[38;5;241m0\u001b[39m:\n\u001b[1;32m    117\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m _DummyExperiment()\n\u001b[0;32m--> 118\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfn\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/pytorch_lightning/loggers/csv_logs.py:169\u001b[0m, in \u001b[0;36mexperiment\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m      0\u001b[0m <Error retrieving source code with stack_data see ipython/ipython#13598>\n",
      "File \u001b[0;32m/opt/conda/lib/python3.11/site-packages/fsspec/implementations/local.py:54\u001b[0m, in \u001b[0;36mmakedirs\u001b[0;34m(self, path, exist_ok)\u001b[0m\n\u001b[1;32m     51\u001b[0m     path \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_strip_protocol(path)\n\u001b[1;32m     52\u001b[0m     os\u001b[38;5;241m.\u001b[39mmakedirs(path, exist_ok\u001b[38;5;241m=\u001b[39mexist_ok)\n\u001b[0;32m---> 54\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mrmdir\u001b[39m(\u001b[38;5;28mself\u001b[39m, path):\n\u001b[1;32m     55\u001b[0m     path \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_strip_protocol(path)\n\u001b[1;32m     56\u001b[0m     os\u001b[38;5;241m.\u001b[39mrmdir(path)\n",
      "File \u001b[0;32m<frozen os>:215\u001b[0m, in \u001b[0;36mmakedirs\u001b[0;34m(name, mode, exist_ok)\u001b[0m\n",
      "File \u001b[0;32m<frozen os>:215\u001b[0m, in \u001b[0;36mmakedirs\u001b[0;34m(name, mode, exist_ok)\u001b[0m\n",
      "File \u001b[0;32m<frozen os>:225\u001b[0m, in \u001b[0;36mmakedirs\u001b[0;34m(name, mode, exist_ok)\u001b[0m\n",
      "\u001b[0;31mPermissionError\u001b[0m: [Errno 13] Permission denied: '/root/saved'"
     ]
    }
   ],
   "source": [
    "trainer.fit(model=model,datamodule=datamodule)\n",
    "trainer.test(model=model,datamodule=datamodule,ckpt_path=\"last\")\n",
    "trainer.test(model=model,datamodule=datamodule,ckpt_path=\"best\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
